### ISSUE TITLE
Getting 404 with sample code

### ISSUE THREAD

**Issue by shaklin-box8** [kgryte/npm-list-package-dependents#2]
Hi, 

i have the following code and i am getting 404:

```
let list = require( 'npm-list-package-dependents' );

list( {'package': 'hiredis'}, clbk );

function clbk( error, list ) {
	if ( error ) {
		console.log(error);
        return;
	}
	console.log( list );
	// returns ['<pkg1>','<pkg2>',...]
}
```

response

```
{ status: 404, message: '' }
```

**Comment by kgryte** [comment]
@shaklin-box8 Yeah, unfortunately, `npm` deprecated its CouchDB API due to scalability, and the only way to get dependents is by actually scraping `npm`. It is possible that, in the future, there will be an API for querying `npm`; atm, there is none. :(
